# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Elaina Wittmer
tagline:          ''
description:      ''
url:              http://el-wittmer.github.io
baseurl:          /

author:
  name:           'Elaina Wittmer'
  url:            http://el-wittmer.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/el-wittmer/el-wittmer.github.io
