# Dependencies
markdown:         kramdown
highlighter:      pygments
gems: [jekyll, jekyll-gist]

# Permalinks
permalink:        pretty

# Setup
title:            Elaina Wittmer
tagline:          'Personal Site'
description:      'testing testing'
url:              http://el-wittmer.github.io
baseurl:          /

author:
  name:           Elaina Wittmer'

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/el-wittmer/el-wittmer.github.io
